create table voc.TFA_ALARM_ACT
(
ALARM_ID bigint,
REC_VERSION bigint,
FP0 bigint,
FP1 bigint,
FP2 bigint,
FP3 bigint,
C_FP0 bigint,
C_FP1 bigint,
C_FP2 bigint,
C_FP3 bigint,
EVENT_TIME date,
TIME_STAMP bigint,
CANCEL_TIME date,
ACTIVE_STATUS bigint,
ORG_SEVERITY bigint,
PROVINCE_NAME varchar (32),
REGION_ID bigint,
REGION_NAME varchar (32),
CITY_NAME varchar (32),
NETWORK_TYPE bigint,
ALARM_SOURCE varchar (255),
OBJECT_CLASS bigint,
PROFESSIONAL_TYPE bigint,
SHEET_NO varchar (255),
SHEET_STATUS bigint,
SHEET_SEND_STATUS bigint,
ORG_TYPE bigint,
LOGIC_ALARM_TYPE bigint,
LOGIC_SUB_ALARM_TYPE bigint,
SUB_ALARM_TYPE bigint,
VENDOR_TYPE varchar (64),
OMC_ID bigint,
OMC_ALARM_ID bigint,
VENDOR_ID bigint,
PROBABLE_CAUSE bigint,
PROBABLE_CAUSE_TXT varchar (1024),
ALARM_ORIGIN bigint,
ACK_FLAG bigint,
ACK_USER bigint,
ACK_TIME date,
NE_LABEL varchar (255),
SITE_NO varchar (255),
NE_LOCATION varchar (255),
CIRCUIT_NO varchar (255),
CHANNEL_TYPE bigint,
EQP_LABEL varchar (255),
EQP_ALIAS varchar (255),
NE_ALIAS varchar (255),
NE_STATUS bigint,
EQP_INT_ID bigint,
NE_ADMIN_STATUS bigint,
ALARM_NE_STATUS bigint,
STANDARD_ALARM_NAME varchar (128),
STANDARD_ALARM_ID varchar (128),
EFFECT_NE bigint,
EFFECT_SERVICE bigint,
SEND_JT_FLAG bigint,
GCSS_CLIENT varchar (255),
GCSS_CLIENT_NAME varchar (255),
GCSS_CLIENT_LEVEL bigint,
GCSS_CLIENT_NUM bigint,
GCSS_SERVICE varchar (255),
GCSS_SERVICE_TYPE varchar (255),
GCSS_SERVICE_LEVEL bigint,
GCSS_SERVICE_NUM bigint,
DEADLINE_TIME date,
EQP_OBJECT_CLASS bigint,
EQP_VERSION varchar (128),
INT_ID bigint,
NE_IP varchar (20),
REMOTE_EQP_LABEL varchar (255),
REMOTE_RESOURCE_STATUS double,
REMOTE_PROJ_SUB_STATUS double,
PROJ_OA_FILE_ID varchar (128),
OBJECT_LEVEL bigint,
INFECT_CUSTOMER_COUNT bigint,
FAILED_REASON varchar (255),
UNSEND_REASON varchar (255),
LAYER_RETE varchar (255),
RELATION_TYPE varchar (64),
AC_RULE_NAME varchar (64),
ALARM_RESOURCE_STATUS bigint,
REMARK_EXIST bigint,
ALARM_REASON varchar (255),
IS_ROOT bigint,
HAS_CHILD bigint,
TITLE_TEXT varchar (255),
DEAL_TIME_LIMIT date,
SHEET_DEAL_DEP varchar (255),
SPECIAL_FIELD23 varchar (255),
INSERT_TIME date,
ALARM_ACT_COUNT bigint,
RESOURCE_STATUS bigint,
CITY_ID bigint,
NMS_NAME varchar (64),
CIRCUIT_ID varchar (255),
ALARM_TITLE bigint,
REDEFINE_TYPE bigint,
REDEFINE_SEVERITY bigint,
VENDOR_SEVERITY varchar (64),
STANDARD_FLAG bigint,
EXTRA_ID1 bigint,
EXTRA_STRING3 varchar (255),
GCSS_CLIENT_GRADE bigint,
GCSS_CLIENT_GRADE_MGT bigint,
TMSC_CAT bigint,
PREPROCESS_MANNER bigint,
PREPROCESS_FLAG bigint,
EXTRA_ID3 bigint
)
;


create table voc.TFA_ALARM_ACT_TXT
(
ALARM_ID bigint,
ALARM_TEXT varchar (32000),
REC_VERSION bigint
)

create table voc.TAI_NEGRP_DEFINE
(
GROUP_ID bigint,
INT_ID bigint,
OBJECT_CLASS bigint,
VENDOR_ID bigint,
TYPE bigint,
USERLABEL varchar (64),
PROVINCE_ID bigint
);

create table voc.TAI_NEGRP_DEFINE
(
GROUP_ID bigint,
INT_ID bigint,
OBJECT_CLASS bigint,
VENDOR_ID bigint,
TYPE bigint,
USERLABEL varchar (64),
PROVINCE_ID bigint
)
